### ISSUE TITLE
Embroidery .dst to .png conversion

### ISSUE THREAD

**Issue by dnyaneshwargit** [EmbroidePy/pyembroidery-CLI#3]
using pyembroidery we have converted .dst file into .png but the output image is not realistic.

**Comment by tatarize** [comment]
It's intended an image of what it sort-of looks like. Things like proper representations of thread, shading, etc that makes for more realistic simulated images seems rather outside the scope here. It would require a real graphics library and a lot of different things applied to the image.  The PNG produced is the best I could do with no external libraries, and required encoding the PNG directly in binary and writing my own line draw algorithm.

**Comment by tatarize** [comment]
I would assume anything more complex than this would not output to PNG but rather do the rendering of the data itself. Which would likely to read the file with pyembroidery directly and not the cli to output to something that somewhat visualizes the thing.

**Comment by dnyaneshwargit** [comment]
Is there any option for .dst file with realistic conversion into .png like wilcom and pulse embroidery software are doing.

**Comment by tatarize** [comment]
They are rendering the actual stitches. Pyembroidery is merely doing the reading and writing into and out of various embroidery formats. You can actually do the legwork of vector rendering, and displaying the content. Josh Varga did some interesting work doing that. ( http://joshvarga.com/ ) And there's plenty of things that can be done but they all require proper work with graphic rendering. And more work to get it to look even better. 

EmbroidePy/pyembroidery#56

**Comment by dnyaneshwargit** [comment]
thanks for your help.
Yes that is very helpful for us.
